### ISSUE TITLE
debug运行错误

### ISSUE THREAD

**Issue by sudo-rm-rf-run** [tgtsml/QtInputMethod_GooglePinyin#1]
你好，我在编译debug时候，运行出现该错误，调试发现在创建KeyboardForm对象，初始化父类QWidget时候就挂掉。不知道你是否遇到同样问题
![微信截图_20190710193829](https://user-images.githubusercontent.com/8653159/60966387-b456b700-a34a-11e9-9a94-07fdd210eae0.png)

**Comment by liukang325** [comment]
我也遇到同样的问题，这个警告断言好像是说不能在QApplication之前创建QWidget，但这里又必须在QApplication之前调用qputenv("QT_IM_MODULE", "tgtsml");
一直忽略就可以了。Release下不会弹警告断言。

**Comment by tgtsml** [comment]
更新了下代码，debug和release都可以
